name: Make new release

on:
  push:
    branches:
      - master
      - development

jobs:
  push_prod_application:
    name: Push Backend Docker image to GitHub Packages
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: PrepareReg Names
        run: |
          echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

      - name: Get version of the project
        id: project-version
        uses: euberdeveloper/ga-project-version@v1.0.1
        with:
          package-manager: 'composer'

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create default .env file.
        run: cp .env.example .env

      - name: Create Release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.project-version.outputs.version }}
          release_name: Release ${{ steps.composer.outputs.version }}
          draft: false
          prerelease: true

      - name: Docker Backend Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: |
            docker.pkg.github.com/${{ env.IMAGE_REPOSITORY }}/ws-server:${{ steps.project-version.outputs.version }}
